# Generated by Django 4.2 on 2023-04-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_product_max_amount_product_min_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_amount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
