# Generated by Django 4.2 on 2023-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_product_min_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ex',
            name='faulty',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
