# Generated by Django 4.2 on 2023-04-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_product_ex_faulty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_ex',
            new_name='Product_extended',
        ),
    ]
