# Generated by Django 4.2 on 2023-04-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_product_max_time_alter_product_min_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_extended',
            name='faulty',
            field=models.CharField(choices=[('YES', 'NO')], max_length=50, null=True),
        ),
    ]
