# Generated by Django 4.2 on 2023-05-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_extended_faulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_extended',
            name='faulty',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True),
        ),
    ]
