# Generated by Django 4.2 on 2023-05-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_product_extended_faulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_extended',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
