# Generated by Django 4.2 on 2023-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_extended_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rented',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('SN', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('faulty', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=50, null=True)),
                ('start_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('period', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
