# Generated by Django 4.2 on 2023-05-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_product_extended_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
