# Generated by Django 4.2 on 2023-05-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_product_available'),
        ('dashboard', '0013_rented_request'),
    ]

    operations = [
    ]
