# Generated by Django 4.2 on 2023-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_0013_product_available_0013_rented_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
