# Generated by Django 4.2 on 2023-05-09 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_request_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
