# Generated by Django 4.2 on 2023-05-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rented_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rented',
            name='explanation',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
