# Generated by Django 4.2 on 2023-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rented_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
