# Generated by Django 4.2 on 2023-05-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_stock_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('SN', models.CharField(max_length=50, null=True)),
                ('report_time', models.DateField()),
                ('category', models.CharField(choices=[('Technical Fault', 'Technical Fault'), ('Mechanical Fault', 'Mechanical Fault'), ('Other', 'Other'), ('NO', 'NO')], max_length=50, null=True)),
                ('fault_description', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product_extended',
            name='faulty',
            field=models.CharField(choices=[('Technical Fault', 'Technical Fault'), ('Mechanical Fault', 'Mechanical Fault'), ('Other', 'Other'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rented',
            name='faulty',
            field=models.CharField(choices=[('Technical Fault', 'Technical Fault'), ('Mechanical Fault', 'Mechanical Fault'), ('Other', 'Other'), ('NO', 'NO')], max_length=50, null=True),
        ),
    ]
