# Generated by Django 4.2 on 2023-05-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_faults_alter_product_extended_faulty_and_more'),
        ('dashboard', '0021_mylist'),
    ]

    operations = [
    ]
