# Generated by Django 4.2 on 2023-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_merge_20230529_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, null=True)),
                ('reciever', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=500, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='faults',
            name='category',
            field=models.CharField(choices=[('Available', 'Available'), ('Technical Fault', 'Technical Fault'), ('Mechanical Fault', 'Mechanical Fault'), ('Other', 'Other'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faults',
            name='fault_description',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='product_extended',
            name='faulty',
            field=models.CharField(choices=[('Available', 'Available'), ('Technical Fault', 'Technical Fault'), ('Mechanical Fault', 'Mechanical Fault'), ('Other', 'Other'), ('NO', 'NO')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rented',
            name='faulty',
            field=models.CharField(choices=[('Available', 'Available'), ('Technical Fault', 'Technical Fault'), ('Mechanical Fault', 'Mechanical Fault'), ('Other', 'Other'), ('NO', 'NO')], max_length=50, null=True),
        ),
    ]
