# Generated by Django 4.2 on 2023-06-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='undreadrec',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='unreadsend',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
